"""
harmonic-balance/docs_engine/bim_export.py
IFC (Industry Foundation Classes) export for BIM interoperability.
Compatible with Revit, ArchiCAD, Solibri, and other BIM software.
"""

import uuid
import time
from datetime import datetime
from typing import Dict, List, Optional, Any
from pathlib import Path
from dataclasses import dataclass

# Try to import IfcOpenShell
try:
    import ifcopenshell
    import ifcopenshell.api
    import ifcopenshell.util.element
    IFC_AVAILABLE = True
except ImportError:
    IFC_AVAILABLE = False


@dataclass
class MaterialProperties:
    """Material physical properties."""
    name: str
    thermal_conductivity: float  # W/mK
    density: float  # kg/m³
    compressive_strength: float  # MPa
    specific_heat: float = 1000  # J/kgK
    porosity: float = 0.3


@dataclass
class BuildingElement:
    """Building element definition."""
    element_type: str  # IfcWall, IfcDoor, IfcWindow, etc.
    name: str
    description: str
    material: MaterialProperties
    geometry: Dict[str, Any]


class IFCExporter:
    """Export Harmonic Habitats geometry to IFC format."""
    
    def __init__(self, project_name: str = "Harmonic Habitat"):
        self.project_name = project_name
        self.model = None
        self.project = None
        self.site = None
        self.building = None
        self.storey = None
        self.owner_history = None
        
        # Material definitions
        self.materials = {}
        
    def create_model(self, site_info: Dict = None) -> Optional[Any]:
        """Create new IFC model with project structure."""
        if not IFC_AVAILABLE:
            return None
        
        # Create blank model
        self.model = ifcopenshell.file(schema="IFC4")
        
        # Create owner history
        self.owner_history = self._create_owner_history()
        
        # Create project
        self.project = self._create_project()
        
        # Create site
        self.site = self._create_site(site_info or {})
        
        # Create building
        self.building = self._create_building()
        
        # Create building storey
        self.storey = self._create_storey("Ground Floor", 0.0)
        
        return self.model
    
    def _create_owner_history(self) -> Any:
        """Create owner history entity."""
        if not IFC_AVAILABLE:
            return None
        
        # Create person
        person = self.model.create_entity(
            "IfcPerson",
            Identification="HH",
            FamilyName="Habitats",
            GivenName="Harmonic"
        )
        
        # Create organization
        org = self.model.create_entity(
            "IfcOrganization",
            Identification="HH",
            Name="Harmonic Habitats",
            Description="Sacred Geometry Engine"
        )
        
        # Create person and organization
        person_org = self.model.create_entity(
            "IfcPersonAndOrganization",
            ThePerson=person,
            TheOrganization=org
        )
        
        # Create application
        app = self.model.create_entity(
            "IfcApplication",
            ApplicationDeveloper=org,
            Version="0.1.0",
            ApplicationFullName="Harmonic Balance",
            ApplicationIdentifier="HB"
        )
        
        # Create owner history
        owner_history = self.model.create_entity(
            "IfcOwnerHistory",
            OwningUser=person_org,
            OwningApplication=app,
            ChangeAction="ADDED",
            CreationDate=int(time.time())
        )
        
        return owner_history
    
    def _create_project(self) -> Any:
        """Create project entity."""
        if not IFC_AVAILABLE:
            return None
        
        project = self.model.create_entity(
            "IfcProject",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            Name=self.project_name,
            Description="3D printed earth dwelling generated by Harmonic Habitats",
            UnitsInContext=self._create_unit_assignment()
        )
        
        return project
    
    def _create_unit_assignment(self) -> Any:
        """Create unit assignment with SI units."""
        if not IFC_AVAILABLE:
            return None
        
        # Length unit (meter)
        length_unit = self.model.create_entity(
            "IfcSIUnit",
            UnitType="LENGTHUNIT",
            Prefix=None,
            Name="METRE"
        )
        
        # Area unit (square meter)
        area_unit = self.model.create_entity(
            "IfcSIUnit",
            UnitType="AREAUNIT",
            Prefix=None,
            Name="SQUARE_METRE"
        )
        
        # Volume unit (cubic meter)
        volume_unit = self.model.create_entity(
            "IfcSIUnit",
            UnitType="VOLUMEUNIT",
            Prefix=None,
            Name="CUBIC_METRE"
        )
        
        # Angle unit (radian)
        angle_unit = self.model.create_entity(
            "IfcSIUnit",
            UnitType="PLANEANGLEUNIT",
            Prefix=None,
            Name="RADIAN"
        )
        
        # Temperature unit (kelvin)
        temp_unit = self.model.create_entity(
            "IfcSIUnit",
            UnitType="THERMODYNAMICTEMPERATUREUNIT",
            Prefix=None,
            Name="KELVIN"
        )
        
        # Create unit assignment
        unit_assignment = self.model.create_entity(
            "IfcUnitAssignment",
            Units=[length_unit, area_unit, volume_unit, angle_unit, temp_unit]
        )
        
        return unit_assignment
    
    def _create_site(self, site_info: Dict) -> Any:
        """Create site entity."""
        if not IFC_AVAILABLE:
            return None
        
        # Default site location (0,0,0)
        placement = self._create_local_placement(None, (0, 0, 0))
        
        site = self.model.create_entity(
            "IfcSite",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            Name="Site",
            Description=site_info.get('description', 'Construction site'),
            ObjectPlacement=placement,
            CompositionType="ELEMENT",
            RefLatitude=site_info.get('latitude'),
            RefLongitude=site_info.get('longitude'),
            RefElevation=site_info.get('elevation', 0.0),
            LandTitleNumber=site_info.get('title_number')
        )
        
        # Relate site to project
        self.model.create_entity(
            "IfcRelAggregates",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            RelatingObject=self.project,
            RelatedObjects=[site]
        )
        
        return site
    
    def _create_building(self) -> Any:
        """Create building entity."""
        if not IFC_AVAILABLE:
            return None
        
        placement = self._create_local_placement(self.site.ObjectPlacement, (0, 0, 0))
        
        building = self.model.create_entity(
            "IfcBuilding",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            Name=self.project_name,
            Description="3D printed earth dwelling",
            ObjectPlacement=placement,
            CompositionType="ELEMENT",
            BuildingAddress=None
        )
        
        # Relate building to site
        self.model.create_entity(
            "IfcRelAggregates",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            RelatingObject=self.site,
            RelatedObjects=[building]
        )
        
        return building
    
    def _create_storey(self, name: str, elevation: float) -> Any:
        """Create building storey."""
        if not IFC_AVAILABLE:
            return None
        
        placement = self._create_local_placement(
            self.building.ObjectPlacement, 
            (0, 0, elevation)
        )
        
        storey = self.model.create_entity(
            "IfcBuildingStorey",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            Name=name,
            Description=f"Building storey at elevation {elevation}m",
            ObjectPlacement=placement,
            CompositionType="ELEMENT",
            Elevation=elevation
        )
        
        # Relate storey to building
        self.model.create_entity(
            "IfcRelAggregates",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            RelatingObject=self.building,
            RelatedObjects=[storey]
        )
        
        return storey
    
    def _create_local_placement(self, relative_to: Any, location: tuple) -> Any:
        """Create local placement."""
        if not IFC_AVAILABLE:
            return None
        
        point = self.model.create_entity(
            "IfcCartesianPoint",
            Coordinates=location
        )
        
        axis = self.model.create_entity(
            "IfcDirection",
            DirectionRatios=(0, 0, 1)
        )
        
        ref_direction = self.model.create_entity(
            "IfcDirection",
            DirectionRatios=(1, 0, 0)
        )
        
        axis_placement = self.model.create_entity(
            "IfcAxis2Placement3D",
            Location=point,
            Axis=axis,
            RefDirection=ref_direction
        )
        
        placement = self.model.create_entity(
            "IfcLocalPlacement",
            RelativePlacement=axis_placement,
            PlacementRelTo=relative_to
        )
        
        return placement
    
    def _generate_guid(self) -> str:
        """Generate IFC-compatible GUID."""
        return str(uuid.uuid4()).upper()
    
    def add_wall(self, name: str, length: float, height: float, 
                thickness: float, position: tuple = (0, 0, 0),
                material: MaterialProperties = None) -> Any:
        """Add a wall to the model."""
        if not IFC_AVAILABLE:
            return None
        
        # Create wall entity
        wall_placement = self._create_local_placement(
            self.storey.ObjectPlacement,
            position
        )
        
        wall = self.model.create_entity(
            "IfcWall",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            Name=name,
            Description="3D printed earth wall",
            ObjectPlacement=wall_placement,
            Tag="W-001"
        )
        
        # Create material and associate
        if material:
            self._assign_material(wall, material)
        
        # Relate wall to storey
        self.model.create_entity(
            "IfcRelContainedInSpatialStructure",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            RelatingStructure=self.storey,
            RelatedElements=[wall]
        )
        
        return wall
    
    def add_door(self, name: str, width: float, height: float,
                position: tuple = (0, 0, 0)) -> Any:
        """Add a door to the model."""
        if not IFC_AVAILABLE:
            return None
        
        placement = self._create_local_placement(
            self.storey.ObjectPlacement,
            position
        )
        
        door = self.model.create_entity(
            "IfcDoor",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            Name=name,
            Description=f"Door {width}m x {height}m",
            ObjectPlacement=placement,
            OverallWidth=width,
            OverallHeight=height
        )
        
        self.model.create_entity(
            "IfcRelContainedInSpatialStructure",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            RelatingStructure=self.storey,
            RelatedElements=[door]
        )
        
        return door
    
    def add_window(self, name: str, width: float, height: float,
                  position: tuple = (0, 0, 0)) -> Any:
        """Add a window to the model."""
        if not IFC_AVAILABLE:
            return None
        
        placement = self._create_local_placement(
            self.storey.ObjectPlacement,
            position
        )
        
        window = self.model.create_entity(
            "IfcWindow",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            Name=name,
            Description=f"Window {width}m x {height}m",
            ObjectPlacement=placement,
            OverallWidth=width,
            OverallHeight=height
        )
        
        self.model.create_entity(
            "IfcRelContainedInSpatialStructure",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            RelatingStructure=self.storey,
            RelatedElements=[window]
        )
        
        return window
    
    def add_roof(self, name: str, area: float, position: tuple = (0, 0, 0)) -> Any:
        """Add a roof to the model."""
        if not IFC_AVAILABLE:
            return None
        
        placement = self._create_local_placement(
            self.storey.ObjectPlacement,
            position
        )
        
        roof = self.model.create_entity(
            "IfcRoof",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            Name=name,
            Description="Roof structure",
            ObjectPlacement=placement,
            ShapeType="FLAT"
        )
        
        self.model.create_entity(
            "IfcRelContainedInSpatialStructure",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            RelatingStructure=self.storey,
            RelatedElements=[roof]
        )
        
        return roof
    
    def add_slab(self, name: str, thickness: float, 
                position: tuple = (0, 0, 0)) -> Any:
        """Add a floor/slab to the model."""
        if not IFC_AVAILABLE:
            return None
        
        placement = self._create_local_placement(
            self.storey.ObjectPlacement,
            position
        )
        
        slab = self.model.create_entity(
            "IfcSlab",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            Name=name,
            Description=f"Floor slab, {thickness}mm thick",
            ObjectPlacement=placement,
            Category="FLOOR"
        )
        
        self.model.create_entity(
            "IfcRelContainedInSpatialStructure",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            RelatingStructure=self.storey,
            RelatedElements=[slab]
        )
        
        return slab
    
    def _assign_material(self, element: Any, material: MaterialProperties):
        """Assign material properties to element."""
        if not IFC_AVAILABLE:
            return
        
        # Create or get material
        mat_name = material.name
        if mat_name not in self.materials:
            ifc_material = self.model.create_entity(
                "IfcMaterial",
                Name=mat_name,
                Description=f"Thermal conductivity: {material.thermal_conductivity} W/mK"
            )
            self.materials[mat_name] = ifc_material
            
            # Add material properties
            self._add_material_properties(ifc_material, material)
        else:
            ifc_material = self.materials[mat_name]
        
        # Create material layer set if wall
        if element.is_a('IfcWall'):
            layer = self.model.create_entity(
                "IfcMaterialLayer",
                Material=ifc_material,
                LayerThickness=0.3,  # 300mm
                IsVentilated=False,
                Name="Earth wall"
            )
            
            layer_set = self.model.create_entity(
                "IfcMaterialLayerSet",
                MaterialLayers=[layer],
                LayerSetName="Wall construction"
            )
            
            layer_set_usage = self.model.create_entity(
                "IfcMaterialLayerSetUsage",
                ForLayerSet=layer_set,
                LayerSetDirection="AXIS2",
                DirectionSense="POSITIVE",
                OffsetFromReferenceLine=0
            )
            
            self.model.create_entity(
                "IfcRelAssociatesMaterial",
                GlobalId=self._generate_guid(),
                OwnerHistory=self.owner_history,
                RelatingMaterial=layer_set_usage,
                RelatedObjects=[element]
            )
        else:
            self.model.create_entity(
                "IfcRelAssociatesMaterial",
                GlobalId=self._generate_guid(),
                OwnerHistory=self.owner_history,
                RelatingMaterial=ifc_material,
                RelatedObjects=[element]
            )
    
    def _add_material_properties(self, material: Any, props: MaterialProperties):
        """Add detailed material properties."""
        if not IFC_AVAILABLE:
            return
        
        # Create property sets
        thermal_props = [
            self.model.create_entity(
                "IfcPropertySingleValue",
                Name="ThermalConductivity",
                Description="Thermal conductivity",
                NominalValue=self.model.create_entity("IfcReal", props.thermal_conductivity),
                Unit=self.model.by_type('IfcSIUnit')[0] if self.model.by_type('IfcSIUnit') else None
            ),
            self.model.create_entity(
                "IfcPropertySingleValue",
                Name="SpecificHeatCapacity",
                Description="Specific heat capacity",
                NominalValue=self.model.create_entity("IfcReal", props.specific_heat),
                Unit=None
            ),
        ]
        
        mechanical_props = [
            self.model.create_entity(
                "IfcPropertySingleValue",
                Name="CompressiveStrength",
                Description="Compressive strength",
                NominalValue=self.model.create_entity("IfcReal", props.compressive_strength),
                Unit=None
            ),
        ]
        
        physical_props = [
            self.model.create_entity(
                "IfcPropertySingleValue",
                Name="Density",
                Description="Material density",
                NominalValue=self.model.create_entity("IfcReal", props.density),
                Unit=None
            ),
            self.model.create_entity(
                "IfcPropertySingleValue",
                Name="Porosity",
                Description="Material porosity",
                NominalValue=self.model.create_entity("IfcReal", props.porosity),
                Unit=None
            ),
        ]
        
        # Create property sets
        thermal_set = self.model.create_entity(
            "IfcPropertySet",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            Name="Pset_MaterialThermal",
            Description="Thermal properties",
            HasProperties=thermal_props
        )
        
        mechanical_set = self.model.create_entity(
            "IfcPropertySet",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            Name="Pset_MaterialMechanical",
            Description="Mechanical properties",
            HasProperties=mechanical_props
        )
        
        # Relate property sets to material
        self.model.create_entity(
            "IfcRelDefinesByProperties",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            RelatingPropertyDefinition=thermal_set,
            RelatedObjects=[material]
        )
        
        self.model.create_entity(
            "IfcRelDefinesByProperties",
            GlobalId=self._generate_guid(),
            OwnerHistory=self.owner_history,
            RelatingPropertyDefinition=mechanical_set,
            RelatedObjects=[material]
        )
    
    def save(self, output_path: Path) -> Path:
        """Save IFC model to file."""
        if not IFC_AVAILABLE:
            return self._create_mock_ifc(output_path)
        
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        self.model.write(str(output_path))
        return output_path
    
    def _create_mock_ifc(self, output_path: Path) -> Path:
        """Create placeholder IFC when IfcOpenShell not available."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        content = f"""ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('{output_path.name}','{datetime.now().strftime('%Y-%m-%dT%H:%M:%S')}',
    ('Harmonic Habitats'),(''),'Harmonic Balance v0.1.0','','');
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#1=IFCPROJECT('{self._generate_guid()}',$,'{self.project_name}',$,$,$,$,$,#2);
#2=IFCUNITASSIGNMENT((#3,#4,#5));
#3=IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
#4=IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.);
#5=IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.);
ENDSEC;
END-ISO-10303-21;
"""
        mock_path = output_path.with_suffix('.ifc')
        with open(mock_path, 'w') as f:
            f.write(content)
        
        return mock_path


def export_geometry_to_ifc(geometry: Dict, project_name: str, 
                           output_path: Path) -> Path:
    """
    Export Harmonic Habitats geometry to IFC.
    
    Args:
        geometry: Geometry data from typologies
        project_name: Project name
        output_path: Output file path
    
    Returns:
        Path to generated IFC file
    """
    exporter = IFCExporter(project_name)
    
    # Create model structure
    site_info = {
        'description': f'{project_name} construction site',
        'elevation': 0.0
    }
    exporter.create_model(site_info)
    
    # Define material
    earth_material = MaterialProperties(
        name="3D Printed Earth",
        thermal_conductivity=1.0,  # W/mK
        density=1800,  # kg/m³
        compressive_strength=3.5,  # MPa
        specific_heat=1000,
        porosity=0.3
    )
    
    # Add building elements based on typology
    if geometry['type'] == 'single_pod':
        diameter = geometry.get('diameter', 6.5)
        radius = diameter / 2
        
        # Add circular wall (approximated as segments)
        segments = 8
        for i in range(segments):
            angle = 2 * math.pi * i / segments
            x = radius * math.cos(angle)
            y = radius * math.sin(angle)
            
            exporter.add_wall(
                name=f"Wall Segment {i+1}",
                length=diameter * math.pi / segments,
                height=3.2,
                thickness=0.3,
                position=(x, y, 0),
                material=earth_material
            )
        
        # Add door
        exporter.add_door(
            name="Main Door",
            width=1.0,
            height=2.1,
            position=(radius, 0, 0)
        )
        
        # Add window
        exporter.add_window(
            name="Window",
            width=0.8,
            height=1.2,
            position=(-radius, 0, 1.2)
        )
        
        # Add roof
        exporter.add_roof(
            name="Roof",
            area=math.pi * radius ** 2,
            position=(0, 0, 3.2)
        )
        
        # Add floor
        exporter.add_slab(
            name="Floor",
            thickness=0.2,
            position=(0, 0, 0)
        )
    
    elif geometry['type'] == 'organic_family':
        length = geometry.get('length', 15.0)
        width = geometry.get('width', 5.6)
        levels = geometry.get('levels', 2)
        
        # Add walls
        exporter.add_wall(
            name="North Wall",
            length=length,
            height=2.8 * levels,
            thickness=0.35,
            position=(0, width/2, 0),
            material=earth_material
        )
        
        exporter.add_wall(
            name="South Wall",
            length=length,
            height=2.8 * levels,
            thickness=0.35,
            position=(0, -width/2, 0),
            material=earth_material
        )
        
        # Add floor
        exporter.add_slab(
            name="Ground Floor",
            thickness=0.2,
            position=(0, 0, 0)
        )
        
        # Add roof
        exporter.add_roof(
            name="Roof",
            area=length * width,
            position=(0, 0, 2.8 * levels)
        )
    
    elif geometry['type'] == 'multi_pod_cluster':
        pod_count = geometry.get('pod_count', 4)
        arrangement_radius = 12.0
        
        # Add each pod
        for i in range(pod_count):
            angle = 2 * math.pi * i / pod_count
            x = arrangement_radius * math.cos(angle)
            y = arrangement_radius * math.sin(angle)
            
            exporter.add_wall(
                name=f"Pod {i+1} Wall",
                length=math.pi * 3.0,  # Circumference approx
                height=3.0,
                thickness=0.3,
                position=(x, y, 0),
                material=earth_material
            )
    
    # Save model
    return exporter.save(output_path)


if __name__ == "__main__":
    print("IFC BIM Export Test")
    
    geometry = {
        'type': 'single_pod',
        'diameter': 6.5,
        'height': 3.2
    }
    
    output_dir = Path(__file__).parent / 'outputs'
    output_path = export_geometry_to_ifc(
        geometry,
        "Test Single Pod",
        output_dir / 'test_model.ifc'
    )
    
    print(f"Exported: {output_path}")
